all:
	g++ -g -std=c++11 service.cpp shader.cpp texture.cpp egl.cpp png.cpp glwrap.cpp httpserver.cpp template.cpp detector.cpp requesthandler.cpp allocator.cpp -lEGL -lGLESv2 -lpng12 -lmicrohttpd -luuid -o service

