---
- hostname:
    name: capter

- name: create user
  user: name=capter shell=/bin/false

- name: copy motd
  copy: src=motd dest=/etc/motd

- name: download golang
  unarchive:
    src: go1.8.1.linux-armv6l.tar.gz
    dest: /usr/local/
    creates: /usr/local/go

- name: add go bin to PATH
  copy: src=go_env.sh dest=/etc/profile.d/go_env.sh owner=root mode=0755

- name: copy service files
  synchronize: 
    src: go
    dest: /home/capter/
    rsync_opts: "--chmod=D0770 --chmod=F0660 --chown=capter:capter"
  notify: enable and restart services

- name: copy capterca
  copy: src=capterca dest=/srv/
  notify: enable and restart services

- name: fix permissions for capterca
  file: name=/srv owner=capter group=capter recurse=yes state=directory

- name: make service executable
  file: path={{item}} mode=0755
  with_items:
    - /home/capter/go/bin/capter
    - /srv/capterca
  notify: enable and restart services

- name: add service files
  copy: src={{ item }}.service dest=/etc/systemd/system/{{ item }}.service
  notify: enable and restart services
  with_items:
    - capter
    - capterca
