- name: copy blink script
  copy: src=blink_green_led.sh dest=/root/blink_green_led.sh owner=root group=root mode=0755
  notify: enable and restart blink_green_led

- name: copy blink_green_led systemd service
  template: src=blink_green_led.service dest=/etc/systemd/system/blink_green_led.service
  notify: enable and restart blink_green_led
