<?php
    require_once __DIR__ . '/../core/Controller.php';

    class ApplicationDetail extends Controller
    {
        public $template = 'application_detail.twig';

        function get()
        {
            try {


            } catch (Exception $e) {

            }
            echo parent::render(); // TODO: Change the autogenerated stub
        }
    }