<?php
    require_once __DIR__ . '/../core/Controller.php';
    require_once __DIR__ . '/../core/Session.php';
    require_once __DIR__ . '/../modal/OrderItem.php';

    class Index extends Controller
    {
        public $template = 'index.twig';

        function get()
        {
            $all_order_item = OrderItem::get_all();
            $cahr_string = '0123456789abcdefghijklmnopqrstuvwxyz';

            $map = [];

            foreach (str_split($cahr_string) as $char_x) {
                $map[$char_x] = [];
                foreach (str_split($cahr_string) as $char_y) {
                    $map[$char_x][$char_y] = 0;
                }
            }
            $max_energy = 0;
            foreach ($all_order_item as $order_item) {
                $x = strtolower($order_item->position_x);
                $y = strtolower($order_item->position_y);
                if (!isset($map[$order_item->position_x][$order_item->position_y])) {

                    $map[$x][$y] = 0;
                    $map[$x][$y] += $order_item->quantity_energy;
                } else {
                    $map[$x][$y] += $order_item->quantity_energy;

                }
                if ($map[$x][$y] > $max_energy) {
                    $max_energy = $map[$x][$y];
                }
            }
            echo parent::render(
                [
                    'map' => $map,
                    'max_energy' => $max_energy,
                    'min_energy' => 0
                ]
            ); // TODO: Change the autogenerated stub
        }
    }