<?php
    require_once __DIR__ . '/../core/Controller.php';
    require_once __DIR__ . '/../core/Session.php';
    class Index extends Controller
    {
        public $template = 'index.twig';

        function get()
        {
            echo parent::render(['is_auth'=>Session::is_authenticated()]); // TODO: Change the autogenerated stub
        }
    }