from random import randint
from hashlib import md5
import string
import random


def rand_word(length):
    return "".join(
       random.choice(string.ascii_lowercase) for _ in range(length))


def generate_random_passenger_name():
    rand_passenger_number = randint(1, 1000)
    rand_occupation = randint(1000, 10000) % len(occupations) - 1
    random_name = "Passenger-{}-{}".format(
        rand_passenger_number,
        occupations[rand_occupation][:10].replace(" ", "-"))
    return random_name


def generate_random_service_name():
    rand_service_num = randint(1, 100000)
    rand_name = randint(1, 50) % len(restaurants) - 1
    return "Provider-{}-{}".format(restaurants[rand_name], rand_service_num)


def generate_random_hash():
    return md5(rand_word(randint(50, 100)).encode()).hexdigest()


restaurants = [
    "Arbys",
    "AuBonPain",
    "BonchonChicken",
    "BurgerKing",
    "CarlsJr",
    "DairyQueen",
    "DominosPizza",
    "DunkinDonuts",
    "FiveGuys",
    "Hardees",
    "HungryJacks",
    "Jollibee",
    "KFC",
    "KrispyKreme",
    "LongJohnSilvers",
    "McDonalds",
    "Nandos",
    "Popeyes",
    "PizzaHut",
    "Quiznos",
    "SonicDriveIn",
    "Starbucks",
    "Subway",
    "TacoBell",
    "TCBY",
    "Fridays",
    "TimHortons",
    "Wendys",
    "WhiteCastle",
    "Wingstop",
    "WingStreet"
]

occupations = [
    "accountant",
    "actor",
    "actuary",
    "adhesive bonding machine tender",
    "adjudicator",
    "administrative assistant",
    "administrative services manager",
    "adult education teacher",
    "advertising manager",
    "advertising sales agent",
    "aerobics instructor",
    "aerospace engineer",
    "aerospace engineering technician",
    "agent",
    "agricultural engineer",
    "agricultural equipment operator",
    "agricultural grader",
    "agricultural inspector",
    "agricultural manager",
    "agricultural sciences teacher",
    "agricultural sorter",
    "agricultural technician",
    "agricultural worker",
    "air conditioning installer",
    "air conditioning mechanic",
    "air traffic controller",
    "aircraft cargo handling supervisor",
    "aircraft mechanic",
    "aircraft service technician",
    "airline copilot",
    "airline pilot",
    "ambulance dispatcher",
    "ambulance driver",
    "apparel patternmaker",
    "apparel worker",
    "arbitrator",
    "archeologist",
    "architect",
    "architectural drafter",
    "architectural manager",
    "archivist",
    "art director",
    "art teacher",
    "artist",
    "assembler",
    "astronomer",
    "athlete",
    "athletic trainer",
    "ATM machine repairer",
    "atmospheric scientist",
    "baker",
    "barback",
    "barber",
    "bartender",
    "basic education teacher",
    "behavioral disorder counselor",
    "bellhop",
    "bench carpenter",
    "bicycle repairer",
    "bill and account collector",
    "billing and posting clerk",
    "biochemist",
    "biological technician",
    "biomedical engineer",
    "biophysicist",
    "blaster",
    "blending machine operator",
    "blockmason",
    "boiler operator",
    "boilermaker",
    "bookkeeper",
    "boring machine tool tender",
    "brazer",
    "brickmason",
    "bridge and lock tender",
    "broadcast news analyst",
    "broadcast technician",
    "brokerage clerk",
    "budget analyst",
    "building inspector",
    "bus mechanic",
    "butcher",
    "buyer",
    "cabinetmaker",
    "cafeteria attendant",
    "cafeteria cook",
    "camera operator",
    "camera repairer",
    "cardiovascular technician",
    "cargo agent",
    "carpenter",
    "carpet installer",
    "cartographer",
    "cashier",
    "caster",
    "ceiling tile installer",
    "cellular equipment installer",
    "chauffeur",
    "checker",
    "chef",
    "chemical engineer",
    "chemical plant operator",
    "chemist",
    "chemistry teacher",
    "chief executive",
    "child social worker",
    "childcare worker",
    "chiropractor",
    "choreographer",
    "civil drafter",
    "civil engineer",
    "civil engineering technician",
    "claims adjuster",
    "claims examiner",
    "claims investigator",
    "cleaner",
    "clinical laboratory technician",
    "clinical laboratory technologist",
    "clinical psychologist",
    "coating worker",
    "coatroom attendant",
    "coil finisher",
    "coil taper",
    "coil winder",
    "coin machine servicer",
    "commercial diver",
    "commercial pilot",
    "commodities sales agent",
    "communications equipment operator",
    "communications teacher",
    "community association manager",
    "community service manager",
    "compensation and benefits manager",
    "compliance officer",
    "composer",
    "computer hardware engineer",
    "computer network architect",
    "computer operator",
    "computer programmer",
    "computer science teacher",
    "computer support specialist",
    "computer systems administrator",
    "computer systems analyst",
    "concierge",
    "conciliator",
    "concrete finisher",
    "conservation science teacher",
    "conservation scientist",
    "conservation worker",
    "conservator",
    "construction inspector",
    "construction manager",
    "construction painter",
    "construction worker",
    "continuous mining machine operator",
    "convention planner",
    "conveyor operator",
    "cook",
    "cooling equipment operator",
    "copy marker",
    "correctional officer",
    "correctional treatment specialist",
    "correspondence clerk",
    "correspondent",
    "cosmetologist",
    "cost estimator",
    "costume attendant",
    "counseling psychologist",
    "counselor",
    "courier",
    "court reporter",
    "craft artist",
    "crane operator",
    "credit analyst",
    "credit checker",
    "credit counselor",
    "criminal investigator",
    "criminal justice teacher",
    "crossing guard",
    "curator",
    "custom sewer",
    "customer service representative",
    "cutter",
    "cutting machine operator",
    "dancer",
    "data entry keyer",
    "database administrator",
    "decorating worker",
    "delivery services driver",
    "demonstrator",
    "dental assistant",
    "dental hygienist",
    "dental laboratory technician",
    "dentist",
    "derrick operator",
    "designer",
    "electrical electronics drafter",
    "electrical engineer",
    "electrical equipment assembler",
    "electrical installer",
    "electrical power-line installer",
    "electrician",
    "electro-mechanical technician",
    "elementary school teacher",
    "elevator installer",
    "ophthalmic laboratory technician",
    "optician",
    "optometrist",
    "oral surgeon",
    "order clerk",
    "order filler",
    "orderly",
    "ordnance handling expert",
    "orthodontist",
    "orthotist",
    "plant scientist",
    "plasterer",
    "plastic patternmaker",
    "plastic worker",
    "plumber",
    "podiatrist",
    "police dispatcher",
    "police officer",
    "policy processing clerk",
    "property manager",
    "prosthetist",
    "prosthodontist",
    "psychiatric aide",
    "psychiatric technician",
    "psychiatrist",
    "psychologist",
    "psychology teacher",
    "public relations manager",
    "public relations specialist",
    "pump operator",
    "purchasing agent",
    "purchasing manager",
    "radiation therapist",
    "rehabilitation counselor",
    "reinforcing iron worker",
    "reinforcing rebar worker",
    "religion teacher",
    "religious activities director",
    "religious worker",
    "rental clerk",
    "repair worker",
    "reporter",
    "residential advisor",
    "resort desk clerk",
    "respiratory therapist",
    "respiratory therapy technician",
    "retail buyer",
    "retail salesperson",
    "revenue agent",
    "rigger",
    "rock splitter",
    "rolling machine tender",
    "roof bolter",
    "roofer",
    "rotary drill operator",
    "roustabout",
    "safe repairer",
    "sailor",
    "sales engineer",
    "sales manager",
    "sales representative",
    "sampler",
    "sawing machine operator",
    "shoe machine operator",
    "shoe worker",
    "short order cook",
    "signal operator",
    "signal repairer",
    "singer",
    "ski patrol",
    "skincare specialist",
    "slaughterer",
    "slicing machine tender",
    "streetcar operator",
    "structural iron worker",
    "structural metal fabricator",
    "structural metal fitter",
    "structural steel worker",
    "stucco mason",
    "substance abuse counselor",
    "substance abuse social worker",
    "subway operator",
    "surfacing equipment operator",
    "surgeon",
    "surgical technologist",
    "survey researcher",
    "surveying technician",
    "surveyor",
    "switch operator",
    "switchboard operator",
    "tailor",
    "tamping equipment operator",
    "tank car loader",
    "taper",
    "tax collector",
    "tax examiner",
    "tax preparer",
    "taxi driver",
    "teacher assistant",
    "teacher",
    "team assembler",
    "technical writer",
    "textile worker",
    "therapist",
    "ticket agent",
    "ticket taker",
    "tile setter",
    "timekeeping clerk",
    "timing device assembler",
    "tire builder",
    "tire changertire repairer",
    "title abstractor",
    "title examiner",
    "word processor",
    "writer",
    "yardmaster",
    "zoologist"]
